name: Linear GitHub Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # 5分ごとに実行
  repository_dispatch:
    types: [linear-webhook]

jobs:
  sync-linear-to-github:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Linear to GitHub Sync
        uses: linearapp/linear-github-sync@v1
        with:
          linear-api-key: ${{ secrets.LINEAR_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          team-id: ${{ secrets.LINEAR_TEAM_ID }}
          project-id: ${{ secrets.LINEAR_PROJECT_ID }}
          
      - name: Create GitHub Issue from Linear
        if: github.event_name == 'repository_dispatch'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const payload = context.payload.client_payload;
            
            if (payload.action === 'create' && payload.type === 'Issue') {
              const issue = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: payload.data.title,
                body: `## Linear Issue: [${payload.data.identifier}](${payload.data.url})\n\n${payload.data.description || ''}`,
                labels: ['linear']
              });
              
              console.log(`Created GitHub issue #${issue.data.number} for Linear ${payload.data.identifier}`);
            }